# 用于前端组件仓库的gitlab-ci配置文件
# 以下变量在gitlab ci variables中定义
# NAMESPACE: 主仓库NAMESPACE
# NPM_REGISTRY: npm仓库地址
# NPM_TOKEN: npm用户凭证

image: node:14

stages:
  - publish
  # - publish

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: npm-cache
  paths:
    - node_modules/

release:
  stage: publish
  tags:
    - Frontend
  script: 
    - cd lib
    - npm install --registry=https://registry.npm.taobao.org/
    - npm config set registry $NPM_REGISTRY
    - npm run ci-publish
  rules:
    - if: '$CI_PROJECT_NAMESPACE == $NAMESPACE && $CI_COMMIT_REF_NAME =~ /^v.*/'
      when: on_success
    - when: never